### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by nagylzs** [va1ngvarr/midjourney_api#1]
Your main function in test.py is not an async function, but you have an "await" inside it. This is a SyntaxError.

**Comment by va1ngvarr** [comment]
Hello. I'm going to publish new version with new features. Thanks a lot for that warn!On Jun 15, 2023 00:16, László Zsolt Nagy ***@***.***> wrote:
Your main function in test.py is not an async function, but you have an "await" inside it. This is a SyntaxError.
